version: '2'

services:

  mpg1:
    image: centos/postgresql-96-centos7
    restart: always
    environment:
      POSTGRESQL_ADMIN_PASSWORD: example
    volumes:
      - ./mpg1:/var/lib/pgsql/data
    networks:
      vpcbr:
        ipv4_address: 192.168.101.11

  mpg2:
    image: centos/postgresql-96-centos7
    restart: always
    environment:
      POSTGRESQL_ADMIN_PASSWORD: example
    volumes:
      - ./mpg2:/var/lib/pgsql/data
    networks:
      vpcbr:
        ipv4_address: 192.168.101.12

  spg1:
    image: centos/postgresql-96-centos7
    restart: always
    environment:
      POSTGRESQL_ADMIN_PASSWORD: example
    volumes:
      - ./spg1:/var/lib/pgsql/data
    networks:
      vpcbr:
        ipv4_address: 192.168.101.21

  spg2:
    image: centos/postgresql-96-centos7
    restart: always
    environment:
      POSTGRESQL_ADMIN_PASSWORD: example
    volumes:
      - ./spg2:/var/lib/pgsql/data
    networks:
      vpcbr:
        ipv4_address: 192.168.101.22


  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:8080
    networks:
      - vpcbr

  nodejs:
    build: ./nodejs
    restart: always
    working_dir: /app
    volumes:
      - ./nodejs/app:/app
    ports:
      - 3000:3000
      - 35729:35729
    command: yarn start
    networks:
      - vpcbr


networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.101.0/16
         gateway: 192.168.101.1
         
         
# networks:
#   widgets:
#     driver: bridge
#     ipam:
#      config:
#        - subnet: 172.17.1.0/24
#          aux_addresses:
#           mpg1: 172.17.1.3
#           mpg2: 172.17.1.4
#           spg1: 172.17.1.5
#           spg2: 172.17.1.6
#           nodejs: 172.17.1.1
#           adminer: 172.17.1.2
# 


  #react-kickstart:
   #  image: react-kickstart
   #volumes:
   #  - ./react-kickstart:/app
   #  ports:
   #   - "3000:3000"

    #command: bash -c "npm install -g create-react-app && create-react-app redux && cd redux && npm start"
    #command: bash -c "npm install --save babel-preset-react"
    #command: bash -c "node server.js"
    #command: npm start